import{a as m,i as g,S as h}from"./assets/vendor-09d7c26e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function i(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=i(e);fetch(e.href,n)}})();const b="45110069-9beca970d71a92a84c606c316",L="https://pixabay.com/api/";async function f(r,t=1,i=15){const o=`${L}?key=${b}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${i}`;try{return(await m.get(o)).data.hits}catch(e){throw console.error("Error fetching images:",e),e}}function p(r){const t=document.querySelector(".gallery"),i=r.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <img src="${o.webformatURL}" alt="${o.tags}" />
      <div class="info">
        <p class="info-item"><strong>Likes:</strong> ${o.likes}</p>
        <p class="info-item"><strong>Views:</strong> ${o.views}</p>
        <p class="info-item"><strong>Comments:</strong> ${o.comments}</p>
        <p class="info-item"><strong>Downloads:</strong> ${o.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",i)}function w(){document.querySelector(".gallery").innerHTML=""}function a(r,t="info"){g[t]({title:r,position:"topRight"})}const $=document.querySelector("#search-form"),c=document.querySelector(".loader"),s=document.createElement("button");s.textContent="Load more";s.classList.add("load-more-btn");document.body.appendChild(s);s.style.display="none";let d=1,l="",y;$.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.query.value.trim(),!l){a("Please enter a search query!","error");return}d=1,w(),s.style.display="none",c.style.display="block";try{const t=await f(l,d);t.length===0?a("Sorry, there are no images matching your search query. Please try again!","error"):(p(t),y=new h(".gallery a"),y.refresh(),s.style.display=t.length===15?"block":"none")}catch{a("An error occurred while fetching images!","error")}finally{c.style.display="none"}});s.addEventListener("click",async()=>{d+=1,c.style.display="block";try{const r=await f(l,d);p(r),y.refresh();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),r.length<15&&(s.style.display="none",a("We're sorry, but you've reached the end of search results.","info"))}catch{a("An error occurred while fetching images!","error")}finally{c.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
